name: todo_list
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  mask_text_input_formatter: ^2.3.0
  http: ^0.13.5
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.14

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true



  assets:
  - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash.png"
